language: csharp
mono: none
dotnet: 3.1.404

script:
  - dotnet restore
  - dotnet build
  - dotnet test --filter "TestCategory != SqlServer"

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh $NUGET_KEY
  on:
    branch: master
    tags: true
