language: csharp
mono: none
dotnet: 5.0.103

script:
  - dotnet restore
  - dotnet build
  - dotnet test

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh $NUGET_KEY
  on:
    branch: master
    tags: true
