# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet build
  displayName: 'Build'

- script: dotnet test
  displayName: 'Test'

- script: dotnet pack -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Package'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'xylab-nuget'
